fix: more robust virtualisation detection

diff --git a/.github/workflows/compose-smoketest.yaml b/.github/workflows/compose-smoketest.yaml
--- a/.github/workflows/compose-smoketest.yaml
+++ b/.github/workflows/compose-smoketest.yaml
@@ -14,12 +14,16 @@ jobs:
         uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
       - name: Install smoketest dependencies
         run: |
-          sudo apt-get update
-          sudo apt-get install --no-install-recommends --yes \
-            bridge-utils \
-            qemu-kvm \
-            qemu-system \
-            qemu-utils
+          if grep -qE "svm|vmx" /proc/cpuinfo; then
+            sudo apt-get update \
+            && sudo apt-get install --no-install-recommends --yes \
+              bridge-utils \
+              qemu-system \
+              qemu-utils
+          else
+            echo "ERROR: System does not support virtualisation"
+            exit 1
+          fi
       - name: Checkout repository vyos/vyos-build
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
         with:
@@ -59,11 +63,11 @@ jobs:
         name: Run smoketest
         run: |
           if sudo $(which uv) run --python 3.14.2 --with pexpect --with tomli ${{ inputs.test_cmd }}; then
-              echo "exit_code_${{ inputs.arch }}=success" >> $GITHUB_OUTPUT
-              exit 0
+            echo "exit_code_${{ inputs.arch }}=success" >> $GITHUB_OUTPUT
+            exit 0
           else
-              echo "exit_code_${{ inputs.arch }}=fail" >> $GITHUB_OUTPUT
-              exit 1
+            echo "exit_code_${{ inputs.arch }}=fail" >> $GITHUB_OUTPUT
+            exit 1
           fi
         working-directory: vyos-build
     timeout-minutes: ${{ inputs.test_timeout }}
