ci: Add development.yaml workflow (#117)

diff --git a/.github/workflows/dev.yaml b/.github/workflows/dev.yaml
--- a/.github/workflows/dev.yaml
+++ b/.github/workflows/dev.yaml
@@ -44,6 +44,11 @@ jobs:
       packages: read
     runs-on: ubuntu-24.04
     steps:
+      # - id: remount_workdir
+      #   name: "Remount the working directory"
+      #   run: |
+      #     set -ex
+      #     mount -i -o remount,exec,dev /__w/
       - id: date_format
         name: "Run `date` and format"
         run: |
@@ -87,6 +92,47 @@ jobs:
           set -eux
           echo "VYOS_1X_COMMIT_SHA=$(git --no-pager log --pretty=format:%H --max-count=1)" >> "$GITHUB_ENV"
         working-directory: packages/vyos-1x
+      # - name: "Build vyos-1x package"
+      #   run: |
+      #     set -eux
+      #     sudo apt-get --no-install-recommends --yes install \
+      #       build-essential:native \
+      #       debhelper \
+      #       dh-python \
+      #       libvyosconfig0 \
+      #       libzmq3-dev \
+      #       pylint \
+      #       python3-lxml \
+      #       python3-xmltodict \
+      #       python3-coverage \
+      #       python3-hurry.filesize \
+      #       python3-nose \
+      #       python3-paramiko \
+      #       python3-passlib \
+      #       python3-psutil \
+      #       python3-tabulate \
+      #       python3-zmq \
+      #       quilt \
+      #       whois
+      #     dpkg-buildpackage -uc -us -tc -b
+      #   working-directory: packages/vyos-1x
+      - env:
+          CA_DIR: data/certificates
+          SHIM_CERT_NAME: vyos-dev-2025-shim
+          VYOS_KERNEL_CERT_NAME: vyos-dev-2025-linux
+        id: secure_boot_keys
+        name: "Generate keys for Secure Boot"
+        run: |
+          set -eux
+          openssl req -new -x509 -newkey rsa:4096 -keyout ${CA_DIR}/${SHIM_CERT_NAME}.key -out ${CA_DIR}/${SHIM_CERT_NAME}.der \
+            -outform DER -days 36500 -subj "/CN=VyOS Networks Secure Boot CA/" -nodes
+          openssl x509 -inform der -in ${CA_DIR}/${SHIM_CERT_NAME}.der -out ${CA_DIR}/${SHIM_CERT_NAME}.pem
+          openssl req -newkey rsa:4096 -sha256 -nodes -keyout ${CA_DIR}/${VYOS_KERNEL_CERT_NAME}.key \
+            -out ${CA_DIR}/${VYOS_KERNEL_CERT_NAME}.csr -outform PEM -days 3650 \
+            -subj "/CN=VyOS Networks Secure Boot Signer 2025 - linux/"
+          openssl x509 -req -in ${CA_DIR}/${VYOS_KERNEL_CERT_NAME}.csr -CA ${CA_DIR}/${SHIM_CERT_NAME}.pem \
+            -CAkey ${CA_DIR}/${SHIM_CERT_NAME}.key -CAcreateserial -out ${CA_DIR}/${VYOS_KERNEL_CERT_NAME}.pem -days 3650 -sha256
+        working-directory: vyos-build
       - id: build_iso
         name: "Build the TBM VyOS ISO"
         run: |
@@ -227,6 +273,73 @@ jobs:
             echo "exit_code=fail" >> $GITHUB_OUTPUT
           fi
     timeout-minutes: 90
+  smoketests_secure_boot:
+    if: ${{ !cancelled() }}
+    name: "Smoketests: Secure Boot"
+    needs: [build_iso]
+    outputs:
+      exit_code: ${{ steps.smoketests_secure_boot.outputs.exit_code }}
+    runs-on: ubuntu-24.04
+    steps:
+      - id: kvm
+        name: "Check KVM support"
+        run: |
+          set -eux
+          sudo apt-get update
+          sudo apt-get --no-install-recommends --yes install \
+            cpu-checker
+          sudo kvm-ok
+          sudo apt-get --no-install-recommends --yes install \
+            cpuid
+          if cpuid | grep -q AMD; then
+            echo "Nested virtualisation enabled: $(cat /sys/module/kvm_amd/parameters/nested)"
+          elif cpuid | grep -q Intel; then
+            echo "Nested virtualisation enabled: $(cat /sys/module/kvm_intel/parameters/nested)"
+          else
+              echo "Unsupported CPU vendor: $(cpuid)" >&2
+              exit 1
+          fi
+      - id: install_deps
+        name: "Install smoketest dependencies"
+        run: |
+          set -eux
+          sudo apt-get --no-install-recommends --yes install \
+            build-essential \
+            ovmf \
+            python3-pexpect \
+            python3-tomli \
+            qemu-system-x86 \
+            qemu-utils
+      - id: enable_kvm
+        name: "Enable KVM support"
+        run: |
+          set -eux
+          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
+          sudo udevadm control --reload-rules
+          sudo udevadm trigger --name-match=kvm
+          sudo usermod -aG kvm runner
+      - id: checkout_vyos_build
+        name: "Fetch the `vyos-build` repository"
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          ref: ${{ needs.build_iso.outputs.vyos_build_commit_sha }}
+          repository: vyos/vyos-build
+      - id: download_iso
+        name: "Download the ISO artifact"
+        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
+        with:
+          name: tbm-vyos-${{ needs.build_iso.outputs.version }}-liveimage
+          path: build
+      - id: smoketests_secure_boot
+        name: "Run smoketests"
+        run: |
+          set -eux
+          sudo make testsb
+          if [ $? = 0 ]; then
+            echo "exit_code=success" >> $GITHUB_OUTPUT
+          else
+            echo "exit_code=fail" >> $GITHUB_OUTPUT
+          fi
   smoketests_raid:
     container:
       image: ${{ inputs.build_container }}
@@ -332,80 +445,7 @@ jobs:
             echo "exit_code=fail" >> $GITHUB_OUTPUT
           fi
     timeout-minutes: 20
-  draft_release:
-    if: ${{ !cancelled() }}
-    name: "Draft release"
-    needs:
-      [
-        build_iso,
-        smoketests_no_interfaces,
-        smoketests_interfaces_only,
-        smoketests_config_load,
-        smoketests_raid,
-        smoketests_tpm,
-        smoketests_vpp
-      ]
-    outputs:
-      release_url: ${{ steps.draft_release.outputs.html_url }}
-    runs-on: ubuntu-24.04
-    steps:
-      - id: download_artifact
-        name: "Download live image artifact"
-        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
-        with:
-          name: tbm-vyos-${{ needs.build_iso.outputs.version }}-liveimage
-          path: build
-      - id: rename_artifact
-        name: "Rename live image artifact"
-        run: |
-          set -eux
-          mv live-image-*.hybrid.iso ${{ needs.build_iso.outputs.release_filename }}
-        working-directory: build
-      - id: draft_release
-        name: "Create draft release"
-        uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 # v1.16.0
-        with:
-          allowUpdates: false
-          artifactContentType: application/x-iso9660-image
-          artifactErrorsFailBuild: true
-          artifacts: build/tbm-vyos-*.iso
-          body: |
-            ### Build Log
-            https://github.com/MattKobayashi/tbm-vyos/actions/runs/${{ github.run_id }}
-
-            ### Smoketest Results
-            * CLI (no interfaces): ${{ needs.smoketests_no_interfaces.outputs.exit_code == 'success' && '✅ passed' || '❌ failed' }}
-            * CLI (interfaces only): ${{ needs.smoketests_interfaces_only.outputs.exit_code == 'success' && '✅ passed' || '❌ failed' }}
-            * Configuration Load: ${{ needs.smoketests_config_load.outputs.exit_code == 'success' && '✅ passed' || '❌ failed' }}
-            * RAID1: ${{ needs.smoketests_raid.outputs.exit_code == 'success' && '✅ passed' || '❌ failed' }}
-            * TPM: ${{ needs.smoketests_tpm.outputs.exit_code == 'success' && '✅ passed' || '❌ failed' }}
-            * VPP: ${{ needs.smoketests_vpp.outputs.exit_code == 'success' && '✅ passed' || '❌ failed' }}
-
-            ### Upstream Comparison
-            Latest included `vyos-build` commit: https://github.com/vyos/vyos-build/commit/${{ needs.build_iso.outputs.vyos_build_commit }}
-            Commits to `vyos-build` since this build: https://github.com/vyos/vyos-build/compare/${{ needs.build_iso.outputs.vyos_build_commit }}...current
-
-            Latest included `vyos-1x` commit: https://github.com/vyos/vyos-1x/commit/${{ needs.build_iso.outputs.vyos_1x_commit }}
-            Commits to `vyos-1x` since this build: https://github.com/vyos/vyos-1x/compare/${{ needs.build_iso.outputs.vyos_1x_commit }}...current
-          draft: true
-          name: TBM VyOS ${{ needs.build_iso.outputs.version }}
-          omitDraftDuringUpdate: true
-          tag: ${{ needs.build_iso.outputs.version }}
-  notify_release:
-    name: "Release notifications"
-    needs: [draft_release]
-    runs-on: ubuntu-24.04
-    steps:
-      - id: pushover
-        name: "Pushover"
-        run: |
-          curl -s \
-            --form-string "token=${{ secrets.PO_APP_TOKEN }}" \
-            --form-string "user=${{ secrets.PO_USER_KEY }}" \
-            --form-string "message=A new draft release has been created!" \
-            --form-string "url=${{ needs.draft_release.outputs.release_url }}" \
-            https://api.pushover.net/1/messages.json
-name: Release
+name: Development
 on:
   workflow_dispatch:
     inputs:
@@ -421,5 +461,3 @@ on:
         description: "Patch version? (leave blank for none)"
         required: false
         type: string
-  schedule:
-    - cron: "0 0 1 * *"
