feat: add ARM64 build support

diff --git a/.github/workflows/iso.yaml b/.github/workflows/iso.yaml
--- a/.github/workflows/iso.yaml
+++ b/.github/workflows/iso.yaml
@@ -6,12 +6,14 @@ jobs:
       options: "--privileged --sysctl net.ipv6.conf.lo.disable_ipv6=0"
     name: Build ISO
     outputs:
-      exit_code: ${{ steps.build_iso.outputs.exit_code }}
-      release_filename: ${{ steps.get_release_filename.outputs.release_filename }}
+      exit_code_amd64: ${{ steps.build_iso.outputs.exit_code_amd64 }}
+      exit_code_arm64: ${{ steps.build_iso.outputs.exit_code_arm64 }}
+      release_filename_amd64: ${{ steps.get_release_filename.outputs.release_filename_amd64 }}
+      release_filename_arm64: ${{ steps.get_release_filename.outputs.release_filename_arm64 }}
     permissions:
       contents: write
       packages: read
-    runs-on: ubuntu-24.04
+    runs-on: ${{ inputs.runner_os }}
     steps:
       - name: Checkout repository vyos/vyos-build
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
@@ -23,7 +25,6 @@ jobs:
       - if: inputs.vyos_build_pr != ''
         name: Merge requested PRs from vyos/vyos-build
         run: |
-          set -eux
           for pr in $(echo "${{ inputs.vyos_build_pr }}"); do
             title=$(curl -s \
               -H "Accept: application/vnd.github+json" \
@@ -47,7 +48,6 @@ jobs:
       - if: inputs.vyos_1x_pr != ''
         name: Merge requested PRs from vyos/vyos-1x
         run: |
-          set -eux
           for pr in $(echo "${{ inputs.vyos_1x_pr }}"); do
             title=$(curl -s \
               -H "Accept: application/vnd.github+json" \
@@ -63,7 +63,6 @@ jobs:
       - id: patch_build_vyos_image
         name: Patch build-vyos-image
         run: |
-          set -eux
           patch <<'EOF'
           ${{ vars.BUILD_VYOS_IMAGE_PATCH }}
           EOF
@@ -71,7 +70,6 @@ jobs:
       - id: patch_default_motd_j2
         name: Patch default_motd.j2
         run: |
-          set -eux
           patch <<'EOF'
           ${{ vars.DEFAULT_MOTD_J2_PATCH }}
           EOF
@@ -79,7 +77,6 @@ jobs:
       - id: patch_defaults_toml
         name: Patch defaults.toml
         run: |
-          set -eux
           patch <<'EOF'
           ${{ vars.DEFAULTS_TOML_PATCH }}
           EOF
@@ -87,7 +84,6 @@ jobs:
       - id: patch_image_installer_py
         name: Patch image_installer.py
         run: |
-          set -eux
           patch <<'EOF'
           ${{ vars.IMAGE_INSTALLER_PY_PATCH }}
           EOF
@@ -95,7 +91,6 @@ jobs:
       - id: patch_system_login_banner_py
         name: Patch system_login_banner.py
         run: |
-          set -eux
           patch <<'EOF'
           ${{ vars.SYSTEM_LOGIN_BANNER_PY_PATCH }}
           EOF
@@ -103,7 +98,6 @@ jobs:
       - id: patch_test_opmode_show_py
         name: Patch test_op-mode_show.py
         run: |
-          set -eux
           patch <<'EOF'
           ${{ vars.TEST_OPMODE_SHOW_PY_PATCH }}
           EOF
@@ -111,7 +105,6 @@ jobs:
       - id: patch_version_py
         name: Patch version.py
         run: |
-          set -eux
           patch <<'EOF'
           ${{ vars.VERSION_PY_PATCH }}
           EOF
@@ -119,7 +112,6 @@ jobs:
       - id: add_minisign_pub
         name: Add TBM Minisign public key
         run: |
-          set -eux
           echo "${{ secrets.MINISIGN_PUB }}" > vyos-build/data/live-build-config/includes.chroot/usr/share/vyos/keys/tbm.minisign.pub
       - env:
           CA_DIR: data/certificates
@@ -128,7 +120,6 @@ jobs:
         id: secure_boot_certs
         name: Generate Secure Boot certificates
         run: |
-          set -eux
           # Shim
           echo "${{ secrets.VYOS_DEV_2025_SHIM }}" > ${CA_DIR}/${SHIM_CERT_NAME}.key
           openssl req -new -x509 -key ${CA_DIR}/${SHIM_CERT_NAME}.key -out ${CA_DIR}/${SHIM_CERT_NAME}.der \
@@ -146,7 +137,6 @@ jobs:
       - id: build_vyos_1x
         name: Build vyos-1x package
         run: |
-          set -eux
           make deb
           cp ../*.deb ../../packages
         timeout-minutes: 10
@@ -154,47 +144,53 @@ jobs:
       - id: build_iso
         name: Build ISO
         run: |
-          set -eux
+          sudo apt-get update
           sudo apt-get --no-install-recommends --quiet=2 install \
             live-build
           sudo make clean
-          sudo --preserve-env ./build-vyos-image \
-            --architecture amd64 \
+          if sudo --preserve-env ./build-vyos-image \
+            --architecture ${{ inputs.arch }} \
             --build-by 'tbm-vyos@tech.bymatt.au' \
             --build-comment 'Please direct all support queries to support@tech.bymatt.au' \
             --build-type release \
             --version ${{ inputs.version }} \
             --custom-package vyos-1x-smoketest \
-            generic
-          if [ $? = 0 ]; then
-            echo "exit_code=success" >> $GITHUB_OUTPUT
-            return 0
+            generic; then
+              echo "exit_code_${{ inputs.arch }}=success" >> $GITHUB_OUTPUT
+              exit 0
           else
-            echo "exit_code=fail" >> $GITHUB_OUTPUT
-            return 1
+              echo "exit_code_${{ inputs.arch }}=fail" >> $GITHUB_OUTPUT
+              exit 1
           fi
         timeout-minutes: 30
         working-directory: vyos-build
       - id: get_release_filename
         name: Get file name of release ISO
         run: |
-          set -eux
-          RELEASE_FILENAME=tbm-$(ls vyos-*.iso)
-          echo "release_filename=$RELEASE_FILENAME" >> "$GITHUB_OUTPUT"
+          RELEASE_FILENAME=tbm-$(ls vyos-*${{ inputs.arch }}-generic.iso | head -n 1)
+          echo "release_filename_${{ inputs.arch }}=$RELEASE_FILENAME" >> "$GITHUB_OUTPUT"
         working-directory: vyos-build/build
       - id: upload-artifact
         name: Upload live image artifact
         uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
         with:
-          name: tbm-vyos-${{ inputs.version }}-liveimage
+          name: tbm-vyos-${{ inputs.arch }}-${{ inputs.version }}-liveimage
           path: vyos-build/build/live-image-*.hybrid.iso
     timeout-minutes: 45
 name: ISO
 on:
   workflow_call:
     inputs:
+      arch:
+        description: CPU architecture of the ISO build
+        required: true
+        type: string
       build_container:
         description: Build container to use
+        required: true
+        type: string
+      runner_os:
+        description: Runner OS to use
         required: true
         type: string
       version:
@@ -218,11 +214,17 @@ on:
         required: false
         type: string
     outputs:
-      exit_code:
-        description: Exit code of the ISO build process
-        value: ${{ jobs.build_iso.outputs.exit_code }}
-      release_filename:
-        description: File name of the release ISO
-        value: ${{ jobs.build_iso.outputs.release_filename }}
+      exit_code_amd64:
+        description: Exit code of the AMD64 ISO build process
+        value: ${{ jobs.build_iso.outputs.exit_code_amd64 }}
+      exit_code_arm64:
+        description: Exit code of the ARM64 ISO build process
+        value: ${{ jobs.build_iso.outputs.exit_code_arm64 }}
+      release_filename_amd64:
+        description: File name of the AMD64 release ISO
+        value: ${{ jobs.build_iso.outputs.release_filename_amd64 }}
+      release_filename_arm64:
+        description: File name of the ARM64 release ISO
+        value: ${{ jobs.build_iso.outputs.release_filename_arm64 }}
 permissions:
   contents: read
