refactor: Rename and add smoketest jobs for Secure Boot, TPM, and VPP (#113)

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -253,15 +253,15 @@ jobs:
             echo "exit_code=fail" >> $GITHUB_OUTPUT
           fi
     timeout-minutes: 90
-  smoketests_raid_install:
+  smoketests_sb:
     container:
       image: ${{ inputs.build_container }}
       options: "--privileged --sysctl net.ipv6.conf.lo.disable_ipv6=0"
     if: ${{ !cancelled() }}
-    name: "Smoketests: RAID1 installation"
+    name: "Smoketests: Secure Boot"
     needs: [build_iso]
     outputs:
-      exit_code: ${{ steps.smoketests_raid_install.outputs.exit_code }}
+      exit_code: ${{ steps.smoketests_sb.outputs.exit_code }}
     runs-on: ubuntu-24.04
     steps:
       - id: checkout_vyos_build
@@ -276,7 +276,40 @@ jobs:
         with:
           name: tbm-vyos-${{ needs.build_iso.outputs.version }}-liveimage
           path: build
-      - id: smoketests_raid_install
+      - id: smoketests_sb
+        name: "Run smoketests"
+        run: |
+          set -ex
+          sudo make testsb
+          if [ $? = 0 ]; then
+            echo "exit_code=success" >> $GITHUB_OUTPUT
+          else
+            echo "exit_code=fail" >> $GITHUB_OUTPUT
+          fi
+  smoketests_raid:
+    container:
+      image: ${{ inputs.build_container }}
+      options: "--privileged --sysctl net.ipv6.conf.lo.disable_ipv6=0"
+    if: ${{ !cancelled() }}
+    name: "Smoketests: RAID1 installation"
+    needs: [build_iso]
+    outputs:
+      exit_code: ${{ steps.smoketests_raid.outputs.exit_code }}
+    runs-on: ubuntu-24.04
+    steps:
+      - id: checkout_vyos_build
+        name: "Fetch the `vyos-build` repository"
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          ref: ${{ needs.build_iso.outputs.vyos_build_commit_sha }}
+          repository: vyos/vyos-build
+      - id: download_iso
+        name: "Download the ISO artifact"
+        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
+        with:
+          name: tbm-vyos-${{ needs.build_iso.outputs.version }}-liveimage
+          path: build
+      - id: smoketests_raid
         name: "Run smoketests"
         run: |
           set -ex
@@ -287,7 +320,7 @@ jobs:
             echo "exit_code=fail" >> $GITHUB_OUTPUT
           fi
     timeout-minutes: 20
-  smoketests_tpm_encryption:
+  smoketests_tpm:
     container:
       image: ${{ inputs.build_container }}
       options: "--privileged --sysctl net.ipv6.conf.lo.disable_ipv6=0"
@@ -295,7 +328,7 @@ jobs:
     name: "Smoketests: TPM encryption"
     needs: [build_iso]
     outputs:
-      exit_code: ${{ steps.smoketests_tpm_encryption.outputs.exit_code }}
+      exit_code: ${{ steps.smoketests_tpm.outputs.exit_code }}
     runs-on: ubuntu-24.04
     steps:
       - id: checkout_vyos_build
@@ -310,7 +343,7 @@ jobs:
         with:
           name: tbm-vyos-${{ needs.build_iso.outputs.version }}-liveimage
           path: build
-      - id: smoketests_tpm_encryption
+      - id: smoketests_tpm
         name: "Run smoketests"
         run: |
           set -ex
@@ -321,6 +354,39 @@ jobs:
             echo "exit_code=fail" >> $GITHUB_OUTPUT
           fi
     timeout-minutes: 20
+  smoketests_vpp:
+    container:
+      image: ${{ inputs.build_container }}
+      options: "--privileged --sysctl net.ipv6.conf.lo.disable_ipv6=0"
+    if: ${{ !cancelled() }}
+    name: "Smoketests: VPP"
+    needs: [build_iso]
+    outputs:
+      exit_code: ${{ steps.smoketests_vpp.outputs.exit_code }}
+    runs-on: ubuntu-24.04
+    steps:
+      - id: checkout_vyos_build
+        name: "Fetch the `vyos-build` repository"
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          ref: ${{ needs.build_iso.outputs.vyos_build_commit_sha }}
+          repository: vyos/vyos-build
+      - id: download_iso
+        name: "Download the ISO artifact"
+        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
+        with:
+          name: tbm-vyos-${{ needs.build_iso.outputs.version }}-liveimage
+          path: build
+      - id: smoketests_vpp
+        name: "Run smoketests"
+        run: |
+          set -ex
+          sudo make test-vpp
+          if [ $? = 0 ]; then
+            echo "exit_code=success" >> $GITHUB_OUTPUT
+          else
+            echo "exit_code=fail" >> $GITHUB_OUTPUT
+          fi
   draft_release:
     if: ${{ !cancelled() }}
     name: "Draft release"
@@ -330,8 +396,10 @@ jobs:
         smoketests_no_interfaces,
         smoketests_interfaces_only,
         smoketests_config_load,
-        smoketests_raid_install,
-        smoketests_tpm_encryption,
+        smoketests_raid,
+        smoketests_sb,
+        smoketests_tpm,
+        smoketests_vpp
       ]
     outputs:
       release_url: ${{ steps.draft_release.outputs.html_url }}
@@ -365,8 +433,10 @@ jobs:
             * CLI (no interfaces): ${{ needs.smoketests_no_interfaces.outputs.exit_code == 'success' && '✅ passed' || '❌ failed' }}
             * CLI (interfaces only): ${{ needs.smoketests_interfaces_only.outputs.exit_code == 'success' && '✅ passed' || '❌ failed' }}
             * Configuration Load: ${{ needs.smoketests_config_load.outputs.exit_code == 'success' && '✅ passed' || '❌ failed' }}
-            * RAID1: ${{ needs.smoketests_raid_install.outputs.exit_code == 'success' && '✅ passed' || '❌ failed' }}
-            * TPM: ${{ needs.smoketests_tpm_encryption.outputs.exit_code == 'success' && '✅ passed' || '❌ failed' }}
+            * RAID1: ${{ needs.smoketests_raid.outputs.exit_code == 'success' && '✅ passed' || '❌ failed' }}
+            * Secure Boot: ${{ needs.smoketests_sb.outputs.exit_code == 'success' && '✅ passed' || '❌ failed' }}
+            * TPM: ${{ needs.smoketests_tpm.outputs.exit_code == 'success' && '✅ passed' || '❌ failed' }}
+            * VPP: ${{ needs.smoketests_vpp.outputs.exit_code == 'success' && '✅ passed' || '❌ failed' }}
 
             ### Upstream Comparison
             Latest included `vyos-build` commit: https://github.com/vyos/vyos-build/commit/${{ needs.build_iso.outputs.vyos_build_commit }}
