ci: add CLI VPP smoketests to release workflow

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -219,7 +219,7 @@ jobs:
         name: Run smoketests
         run: |
           set -eux
-          sudo make test-no-interfaces
+          sudo make test-no-interfaces-no-vpp
           if [ $? = 0 ]; then
             echo "exit_code=success" >> $GITHUB_OUTPUT
             return 0
@@ -269,6 +269,55 @@ jobs:
         run: |
           set -eux
           sudo make test-interfaces
+          if [ $? = 0 ]; then
+            echo "exit_code=success" >> $GITHUB_OUTPUT
+            return 0
+          else
+            echo "exit_code=fail" >> $GITHUB_OUTPUT
+            return 1
+          fi
+    timeout-minutes: 180
+  smoketests_cli_vpp:
+    container:
+      image: ${{ inputs.build_container }}
+      options: "--privileged --sysctl net.ipv6.conf.lo.disable_ipv6=0"
+    if: |
+      !cancelled() && 
+      needs.build_iso.result == 'success'
+    name: "Smoketests: CLI (VPP)"
+    needs: [build_iso]
+    outputs:
+      exit_code: ${{ steps.smoketests_cli_vpp.outputs.exit_code }}
+    permissions:
+      contents: read
+      packages: read
+    runs-on: ubuntu-24.04
+    steps:
+      - id: checkout_vyos_build
+        name: Checkout repository vyos/vyos-build
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          ref: ${{ needs.build_iso.outputs.vyos_build_commit_sha }}
+          repository: vyos/vyos-build
+      - id: patch_check_qemu_install
+        name: Patch the check-qemu-install script
+        run: |
+          set -eux
+          patch <<'EOF'
+          ${{ vars.CHECK_QEMU_INSTALL_PATCH }}
+          EOF
+        working-directory: scripts
+      - id: download_iso
+        name: Download the ISO artifact
+        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
+        with:
+          name: tbm-vyos-${{ needs.build_iso.outputs.version }}-liveimage
+          path: build
+      - id: smoketests_cli_vpp
+        name: Run smoketests
+        run: |
+          set -eux
+          sudo make test-vpp
           if [ $? = 0 ]; then
             echo "exit_code=success" >> $GITHUB_OUTPUT
             return 0
@@ -479,6 +528,7 @@ jobs:
       needs.build_iso.result == 'success' &&
       needs.smoketests_cli.result == 'success' &&
       needs.smoketests_cli_interfaces.result == 'success' &&
+      needs.smoketests_cli_vpp.result == 'success' &&
       needs.smoketests_config.result == 'success' &&
       needs.smoketests_config_vpp.result == 'success' &&
       needs.smoketests_raid.result == 'success' &&
@@ -489,6 +539,7 @@ jobs:
         build_iso,
         smoketests_cli,
         smoketests_cli_interfaces,
+        smoketests_cli_vpp,
         smoketests_config,
         smoketests_config_vpp,
         smoketests_raid,
@@ -538,6 +589,7 @@ jobs:
             ### Smoketest Results
             * CLI: ${{ needs.smoketests_cli.outputs.exit_code == 'success' && '✅ passed' || '❌ failed' }}
             * CLI (interfaces): ${{ needs.smoketests_cli_interfaces.outputs.exit_code == 'success' && '✅ passed' || '❌ failed' }}
+            * CLI (VPP): ${{ needs.smoketests_cli_vpp.outputs.exit_code == 'success' && '✅ passed' || '❌ failed' }}
             * Configuration Load: ${{ needs.smoketests_config.outputs.exit_code == 'success' && '✅ passed' || '❌ failed' }}
             * Configuration Load (VPP): ${{ needs.smoketests_config_vpp.outputs.exit_code == 'success' && '✅ passed' || '❌ failed' }}
             * RAID1 Installation: ${{ needs.smoketests_raid.outputs.exit_code == 'success' && '✅ passed' || '❌ failed' }}
