refactor: run smoketests in parallel on a single runner

diff --git a/.github/workflows/smoketest.yaml b/.github/workflows/smoketest.yaml
--- a/.github/workflows/smoketest.yaml
+++ b/.github/workflows/smoketest.yaml
@@ -31,9 +31,7 @@ jobs:
       actions: read
       contents: read
       packages: write
-    runs-on:
-      group: ${{ matrix.runner_group }}
-      labels: ${{ matrix.runner_label }}
+    runs-on: ${{ inputs.runner_label }}
     steps:
       # - if: github.event_name == 'workflow_call'
       #   name: Random delay (0-5 minutes)
@@ -54,10 +52,10 @@ jobs:
             echo "TBM_VYOS_PATCH_TOKEN is required to read techbymatt/tbm-vyos-patch" >&2
             exit 1
           fi
- 
+
           sudo apt update
           sudo apt install --no-install-recommends --yes gh
-  
+
           mkdir patch/
           for file in \
             vyos-1x_changes.patch \
@@ -69,7 +67,7 @@ jobs:
               "/repos/techbymatt/tbm-vyos-patch/contents/${file}" \
               > "patch/${file}"
           done
- 
+
           echo ""
           echo "Contents of $(pwd)/patch:"
           ls -halp patch/
@@ -83,12 +81,7 @@ jobs:
       - if: inputs.vyos_build_pr != ''
         name: Merge requested PRs from vyos/vyos-build
         run: |
-          for pr in $(echo "${{ inputs.vyos_build_pr }}"); do
-            title=$(curl -s \
-              -H "Accept: application/vnd.github+json" \
-              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-              "https://api.github.com/repos/vyos/vyos-build/pulls/${pr}" | \
-              jq -r .title)
+          for pr in ${{ inputs.vyos_build_pr }}; do
             git config user.email "tbm-vyos@tech.bymatt.au"
             git config user.name "TBM VyOS"
             git fetch origin "pull/${pr}/head:pr-${pr}"
@@ -118,16 +111,86 @@ jobs:
           path: vyos-build/build
           run-id: ${{ fromJson(inputs.build_run) }}
       - id: run_smoketest
-        name: Run smoketest
+        name: Run smoketests
+        working-directory: vyos-build
         run: |
-          if sudo ${{ inputs.test_cmd }}; then
-                echo "result_${{ inputs.test }}_${{ inputs.arch }}=success" >> $GITHUB_OUTPUT
-                exit 0
+          sudo make test-no-interfaces-no-vpp &
+          pid_cli=$!
+          sudo make test-interfaces &
+          pid_cli_interfaces=$!
+          sudo make test-vpp &
+          pid_cli_vpp=$!
+          sudo make testc &
+          pid_config=$!
+          sudo make testcvpp &
+          pid_config_vpp=$!
+          sudo make testraid &
+          pid_raid=$!
+          sudo make testsb &
+          pid_secureboot=$!
+          sudo make testtpm &
+          pid_tpm=$!
+
+          fail=0
+
+          if wait "$pid_cli"; then
+            echo "result_cli_${{ inputs.arch }}=success" >> "$GITHUB_OUTPUT"
           else
-            echo "result_${{ inputs.test }}_${{ inputs.arch }}=fail" >> $GITHUB_OUTPUT
-            exit 1
+            echo "result_cli_${{ inputs.arch }}=fail" >> "$GITHUB_OUTPUT"
+            fail=1
           fi
-        timeout-minutes: ${{ inputs.build_run && fromJson(inputs.test_timeout) || inputs.test_timeout }}
+
+          if wait "$pid_cli_interfaces"; then
+            echo "result_cli-interfaces_${{ inputs.arch }}=success" >> "$GITHUB_OUTPUT"
+          else
+            echo "result_cli-interfaces_${{ inputs.arch }}=fail" >> "$GITHUB_OUTPUT"
+            fail=1
+          fi
+
+          if wait "$pid_cli_vpp"; then
+            echo "result_cli-vpp_${{ inputs.arch }}=success" >> "$GITHUB_OUTPUT"
+          else
+            echo "result_cli-vpp_${{ inputs.arch }}=fail" >> "$GITHUB_OUTPUT"
+            fail=1
+          fi
+
+          if wait "$pid_config"; then
+            echo "result_config_${{ inputs.arch }}=success" >> "$GITHUB_OUTPUT"
+          else
+            echo "result_config_${{ inputs.arch }}=fail" >> "$GITHUB_OUTPUT"
+            fail=1
+          fi
+
+          if wait "$pid_config_vpp"; then
+            echo "result_config-vpp_${{ inputs.arch }}=success" >> "$GITHUB_OUTPUT"
+          else
+            echo "result_config-vpp_${{ inputs.arch }}=fail" >> "$GITHUB_OUTPUT"
+            fail=1
+          fi
+
+          if wait "$pid_raid"; then
+            echo "result_raid_${{ inputs.arch }}=success" >> "$GITHUB_OUTPUT"
+          else
+            echo "result_raid_${{ inputs.arch }}=fail" >> "$GITHUB_OUTPUT"
+            fail=1
+          fi
+
+          if wait "$pid_secureboot"; then
+            echo "result_secureboot_${{ inputs.arch }}=success" >> "$GITHUB_OUTPUT"
+          else
+            echo "result_secureboot_${{ inputs.arch }}=fail" >> "$GITHUB_OUTPUT"
+            fail=1
+          fi
+
+          if wait "$pid_tpm"; then
+            echo "result_tpm_${{ inputs.arch }}=success" >> "$GITHUB_OUTPUT"
+          else
+            echo "result_tpm_${{ inputs.arch }}=fail" >> "$GITHUB_OUTPUT"
+            fail=1
+          fi
+
+          exit "$fail"
+        timeout-minutes: 180
 name: Smoketest
 on:
   workflow_call:
@@ -145,18 +208,6 @@ on:
         description: Runner label to use
         required: true
         type: string
-      test:
-        description: Name of the smoketest
-        required: true
-        type: string
-      test_cmd:
-        description: Smoketest command to execute
-        required: true
-        type: string
-      test_timeout:
-        description: Timeout for the smoketest
-        required: true
-        type: number
       version:
         description: The version string to use when building the ISO
         required: true
@@ -242,18 +293,6 @@ on:
         description: Runner label to use
         required: true
         type: string
-      test:
-        description: Name of the smoketest
-        required: true
-        type: string
-      test_cmd:
-        description: Smoketest command to execute
-        required: true
-        type: string
-      test_timeout:
-        description: Timeout for the smoketest in minutes
-        required: true
-        type: number
       version:
         description: The version string of the built ISO
         required: true
