chore(ci): Add smoketest result output

diff --git a/.github/workflows/tbm-vyos.yaml b/.github/workflows/tbm-vyos.yaml
--- a/.github/workflows/tbm-vyos.yaml
+++ b/.github/workflows/tbm-vyos.yaml
@@ -155,6 +155,8 @@ jobs:
       options: "--privileged --sysctl net.ipv6.conf.lo.disable_ipv6=0"
     name: Run CLI smoketests (no interfaces)
     needs: [build-iso]
+    outputs:
+      exit_code: ${{ steps.smoketests-no-interfaces.outputs.exit_code }}
     runs-on: smoketests-no-interfaces
     steps:
       - name: "Fetch the `vyos-build` repository"
@@ -173,6 +175,11 @@ jobs:
         run: |
           set -ex
           sudo make test-no-interfaces
+          if [[ $? == 0 ]]; then
+            echo "exit_code=success" >> $GITHUB_OUTPUT
+          else
+            echo "exit_code=fail" >> $GITHUB_OUTPUT
+          fi
     timeout-minutes: 180
   smoketests-interfaces-only:
     container:
@@ -180,6 +187,8 @@ jobs:
       options: "--privileged --sysctl net.ipv6.conf.lo.disable_ipv6=0"
     name: Run CLI smoketests (interfaces only)
     needs: [build-iso]
+    outputs:
+      exit_code: ${{ steps.smoketests-interfaces-only.outputs.exit_code }}
     runs-on: smoketests-interfaces-only
     steps:
       - name: "Fetch the `vyos-build` repository"
@@ -198,6 +207,11 @@ jobs:
         run: |
           set -ex
           sudo make test-interfaces
+          if [[ $? == 0 ]]; then
+            echo "exit_code=success" >> $GITHUB_OUTPUT
+          else
+            echo "exit_code=fail" >> $GITHUB_OUTPUT
+          fi
     timeout-minutes: 180
   smoketests-config-load:
     container:
@@ -205,6 +219,8 @@ jobs:
       options: "--privileged --sysctl net.ipv6.conf.lo.disable_ipv6=0"
     name: Run configuration load smoketests
     needs: [build-iso]
+    outputs:
+      exit_code: ${{ steps.smoketests-config-load.outputs.exit_code }}
     runs-on: smoketests-config-load
     steps:
       - name: "Fetch the `vyos-build` repository"
@@ -223,6 +239,11 @@ jobs:
         run: |
           set -ex
           sudo make testc
+          if [[ $? == 0 ]]; then
+            echo "exit_code=success" >> $GITHUB_OUTPUT
+          else
+            echo "exit_code=fail" >> $GITHUB_OUTPUT
+          fi
     timeout-minutes: 90
   smoketests-raid-install:
     container:
@@ -230,6 +251,8 @@ jobs:
       options: "--privileged --sysctl net.ipv6.conf.lo.disable_ipv6=0"
     name: Run RAID1 installation smoketests
     needs: [build-iso]
+    outputs:
+      exit_code: ${{ steps.smoketests-raid-install.outputs.exit_code }}
     runs-on: smoketests-raid-install
     steps:
       - name: "Fetch the `vyos-build` repository"
@@ -248,6 +271,11 @@ jobs:
         run: |
           set -ex
           sudo make testraid
+          if [[ $? == 0 ]]; then
+            echo "exit_code=success" >> $GITHUB_OUTPUT
+          else
+            echo "exit_code=fail" >> $GITHUB_OUTPUT
+          fi
     timeout-minutes: 20
   smoketests-tpm-encryption:
     container:
@@ -255,6 +283,8 @@ jobs:
       options: "--privileged --sysctl net.ipv6.conf.lo.disable_ipv6=0"
     name: Run TPM encryption smoketests
     needs: [build-iso]
+    outputs:
+      exit_code: ${{ steps.smoketests-tpm-encryption.outputs.exit_code }}
     runs-on: smoketests-tpm-encryption
     steps:
       - name: "Fetch the `vyos-build` repository"
@@ -273,6 +303,11 @@ jobs:
         run: |
           set -ex
           sudo make testtpm
+          if [[ $? == 0 ]]; then
+            echo "exit_code=success" >> $GITHUB_OUTPUT
+          else
+            echo "exit_code=fail" >> $GITHUB_OUTPUT
+          fi
     timeout-minutes: 20
   draft-release:
     name: Create a new draft release
@@ -310,6 +345,12 @@ jobs:
           artifacts: "build/tbm-vyos-*.iso"
           body: |
             Build log: https://github.com/MattKobayashi/tbm-vyos/actions/runs/${{ github.run_id }}
+
+            * CLI Smoketests (no interfaces) ${{ needs.smoketests-no-interfaces.outputs.exit_code == 'success' && '✅ passed' || '❌ failed' }}
+            * CLI Smoketests (interfaces only) ${{ needs.smoketests-interfaces-only.outputs.exit_code == 'success' && '✅ passed' || '❌ failed' }}
+            * Config tests ${{ needs.smoketests-config-load.outputs.exit_code == 'success' && '✅ passed' || '❌ failed' }}
+            * RAID1 tests ${{ needs.smoketests-raid-install.outputs.exit_code == 'success' && '✅ passed' || '❌ failed' }}
+            * TPM tests ${{ needs.smoketests-tpm-encryption.outputs.exit_code == 'success' && '✅ passed' || '❌ failed' }}
 
             Latest included `vyos-build` commit: https://github.com/vyos/vyos-build/commit/${{ needs.build-iso.outputs.vyos-build-commit }}
             Commits to `vyos-build` since this build: https://github.com/vyos/vyos-build/compare/${{ needs.build-iso.outputs.vyos-build-commit }}...current
